### ISSUE TITLE
Display 1 style changes

### ISSUE THREAD

**Issue by likello** [osu-wams/madrone#159]
we'd like to offer Stratum as an option for display fonts, so we've picked display 1 to have it: 

`.display-1 {
	font-family: "Stratum2Web", serif !important;
	line-height: 1 !important;
	font-weight: 500;
}`

this is my override in the homepage

**Comment by emerham** [comment]
We have a class font-stratum2web that will update the font to be stratum

**Comment by likello** [comment]
sorry about the confusion when chatting about this. we want the Display-1 style to be changed to this styling specifically. it's nice to have the font as a class, but this style needs to change for the display-1 option.
