### ISSUE TITLE
architects can't access add custom block admin menu item

### ISSUE THREAD

**Issue by likello** [osu-wams/madrone#270]
this is what architects see in the admin menu: 
![image](https://github.com/user-attachments/assets/95e515ba-f689-4596-b709-a9c2e993b99d)
this is what a dx admin sees: 
![image](https://github.com/user-attachments/assets/e5a027b3-946c-4f2b-a058-f187d011e853)

**Comment by likello** [comment]
this was in today.dev.o.e but Kelsi said that she also saw this in her sandbox site, which she is an architect for

**Comment by likello** [comment]
this isn't the case for health.o.e for Alan and he is an architect

**Comment by emerham** [comment]
Drupal 10 change the block menuing and moved the Block library list under Content and Admin Toolbar has finally updated to show that.

Structure -> Block Types to manage the blocks types
Structure -> Block Layout to manage placements
Content -> Blocks to manage the custom block library
![Screenshot from 2024-08-29 15-00-16](https://github.com/user-attachments/assets/4b61ac72-871e-4fe4-bcd9-e556d644570a)
![Screenshot from 2024-08-29 14-54-15](https://github.com/user-attachments/assets/26140821-e563-468e-b0c0-27c72af8d10c)

**Comment by emerham** [comment]
Might have to make an announcement in how the administrative menu items have moved.
