### ISSUE TITLE
Risky data exposed 

### ISSUE THREAD

**Issue by conf-test** [osu-wams/madrone#63]
Hi,
 
I'm a security researcher and am doing some study of public docker images. I found some misconfigurations in your docker image **_osuwams/drupal_** that may expose some sensitive data. I want to report these potential issues to you so you can fix them if necessary.
 
The data exposure I found includes:
1. phpunit files: like /sites/all/libraries/jsonpath/phpunit.xml, /sites/all/modules/xautoload/phpunit.xml.dist, /sites/all/libraries/spyc/phpunit.xml

* `phpunit.xml` is for unit testing.  You should not leave them on a live production server.  ([ref](https://stackoverflow.com/questions/11078572/should-i-use-phpunit-in-a-staging-production-environment))

Would it be better to block these accesses in your docker image? If you want, I can also help fix them by creating pull requests on your git repo. Please let me know what you think. Thanks!
 
Best Regards,

**Comment by emerham** [comment]
Thanks, Works as designed.
